export const faucetMnemonic = 'express ice hill wife creek season cattle rally excess jungle envelope loyal ship arm lyrics scorpion omit audit breeze butter year gym prepare nothing';

// Called Test Wallet in Wasabi
export const exchangeMnemonic = 'ecology potato outdoor effort manage pudding stand goose access library tongue link';
export const exchangeVprv = 'vprv9KfvPsn5iW9ae48wkknSAePpmZ4qgP7VmeK4rLt64hdTG4h8a7uCCoVG2LWyBFu9hQNLJNzN4sQ2i4tNNfYCixfcpCe4E49wLMG1jJH4t8m';
export const exchangeVpub = 'vpub5YfGoPJyYshsrYDQrnKSXnLZKauL5qqM8sEfejHhd3AS8s2H7fDSkbojsc2smvyh8XPtPiPABW4iRBoGTm83nhUrjhN8aMGSfPhZJHNgsYF';

export const exchangeTrpv = 'tprv8gNjQXVmyPVwp8xNaFYXcy1a21XcJ4xf1GARBUgegYwJRywph7RmyvD8d66KUuFZLAY7DDTfzXTpzibHduBs8qNsc74KncXHopYX6StaHqr';
export const exchangeTpub = 'tpubDD4mYwY27mBchbzATuD82Nfgb33YTQ9ZaZmCTzix6pjhGUCbKWFNAQpzoCyhowoBU5C6NoSR8PbsAXdoxmHth5kthunvctcCTkuYqjZqMAx';

export const exchangeUrpv = 'uprv8zg6xN9gmC7AwtTDfGcLoz5xppXSZZ4To1XHg683aDTvK2JnTzNciZqyS9oJZ4gDb3qqB71SkFLf7c86p3GjzjUPonvU3PRFjaaUdgnQw5G';
export const exchangeUpub = 'upub5DfTMsgabZfUANXgmJ9MB82hNrMvy1nKAEStUUXf8YzuBpdw1XgsGNATHTHYPHd7Y3YVzgNwbzmsAkatLfr6UfZGViRqLh1WzGLDdVSd1wW';

// Called Test Wallet 2 in Wasabi
export const registryMnemonic = 'dad license consider endorse tent menu program north account liberty gym pond';

// Testnet faucet zpub
// eslint-disable-next-line
export const faucetZpub = 'vpub5Zb343d4C86UgNGhiCxjwoPfZ2zGhzTvBjrtZsPjZw246qQ72GRbFzTe4THNvEcB6HiNjPHiLnZQLc6TWBDkbWvSDGLWxmwZYvPr8CuNwHh';

// Testnet registry zpub
// eslint-disable-next-line
export const testnetRegistryZpub = 'vpub5Z7AmECAtX3ex98smKbCMdtvhaUxxzsGHbVFpkuSLXQ4jcHuaDUVU5WT1F1i1BCzc7zQneJXq1S7WZW7N9L7DpeXjYZSeu71yegfzddPQC8'
// eslint-disable-next-line
export const testnetRegistryZprv = 'vprv9L7pMifH49VMjf4QfJ4BzVxC9YeUZY9QvNZf2NVpnBs5roxm2gAEvHBy9yw4oFAU959dN2zvEoHmG1PXswKcbPViSei4khknd1evid84WHi'

export const oldTestnetExchangeZpub = 'vpub5ZrLUWoaJgLrP6TmvJMNZoo1oahKh5eEeV2Bx7ZtuV3tW3NMDrwarVgHm4XNUGNyySXut1QpkZj4AyVop8UAFt6o5qaRUTxjvkhM1QUT9E2'
export const oldTestnetExchangeZprv = 'vprv9Lrz51GgUJnZAcPJpGpNCfrHFYrqHcvPHG6b9jAHM9WudF3CgKdLJhMoupiMzRcXkTxN33FwKCt8YQHP3aitmx3FaGbSXmCQ91qJz2NTqPE'

export const simonsTestnetWallet = 'vpub5VQo2D8FiCNgQcwBYPfgAVAW2FQ7QQViFLPuRb1SLQxEfBTFSJJgGUUkfiPF8r33HKdB4pQM9gKjoK4P8sPWfQGKxU87Mmih2acWSdJjmR3'
export const simonsTestnetWallet2 = 'vpub5ZoiA74btTko95S4iofUVbmFNgfoDFFBZ7MTxiNGFQfwHvJcuqGwsVz2fUgUkBqmgDDVgpBAxHt7Y7aKYczzQ2PXJzKSM2qA3vqanHsAWut'

const newWallet = 'moral anxiety else scale donor piece dream lecture exist super fortune cliff';
