name: Crypto Registry

on:
  push:
    branches-ignore:
    - prod

jobs:
  registry-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: API Install
        working-directory: ./api
        run: npm install

      - name: API Tests
        working-directory: ./api
        run: npm run test

      - name: API Lint
        working-directory: ./api
        run: npm run lint

      - name: Client Install
        working-directory: ./client
        run: npm install

      - name: Client Lint
        working-directory: ./clint
        run: npm run lint
